#!/usr/bin/env python3
"""Generate a comprehensive MQL5 test file with 10,000+ lines."""

def generate_large_mql5_file():
    """Generate a realistic MQL5 file with various constructs."""
    lines = []
    
    # Header and properties
    lines.append("// Large MQL5 Test File - Generated for Parser Testing")
    lines.append("// This file contains 10,000+ lines with 200+ functions and 30+ classes")
    lines.append("")
    lines.append("#property copyright \"MQL5 CodeGraph Test Suite\"")
    lines.append("#property link      \"https://github.com/avangardistic/mql5-codegraph\"")
    lines.append("#property version   \"1.00\"")
    lines.append("#property strict")
    lines.append("#property script_show_inputs")
    lines.append("")
    
    # Includes
    lines.append("#include <Trade/Trade.mqh>")
    lines.append("#include <Trade/PositionInfo.mqh>")
    lines.append("#include <Trade/SymbolInfo.mqh>")
    lines.append("#include <Trade/AccountInfo.mqh>")
    lines.append("#include <Trade/OrderInfo.mqh>")
    lines.append("#include <Trade/DealInfo.mqh>")
    lines.append("#include <Indicators/MACD.mqh>")
    lines.append("#include <Indicators/RSI.mqh>")
    lines.append("#include <Indicators/MA.mqh>")
    lines.append("#include <Indicators/Stochastic.mqh>")
    lines.append("#include <Controls/Dialog.mqh>")
    lines.append("")
    
    # Defines
    lines.append("// Macro definitions")
    for i in range(20):
        lines.append(f"#define MACRO_{i}(x) ((x) * {i + 1})")
    lines.append("")
    
    # Enums
    lines.append("// Enum definitions")
    for i in range(15):
        lines.append(f"enum ENUM_TEST_{i}")
        lines.append("  {")
        for j in range(5):
            lines.append(f"   VALUE_{i}_{j},")
        lines.append("  };")
        lines.append("")
    
    # Structs
    lines.append("// Struct definitions")
    for i in range(15):
        lines.append(f"struct STestStruct{i}")
        lines.append("  {")
        lines.append(f"   int field_a{i};")
        lines.append(f"   double field_b{i};")
        lines.append(f"   string field_c{i};")
        lines.append(f"   bool field_d{i};")
        lines.append(f"   datetime field_e{i};")
        lines.append("  };")
        lines.append("")
    
    # Unions
    lines.append("// Union definitions")
    for i in range(5):
        lines.append(f"union UTestData{i}")
        lines.append("  {")
        lines.append(f"   int int_val{i};")
        lines.append(f"   double double_val{i};")
        lines.append(f"   long long_val{i};")
        lines.append("  };")
        lines.append("")
    
    # Classes with inheritance
    lines.append("// Base class")
    lines.append("class CBaseStrategy")
    lines.append("  {")
    lines.append("protected:")
    lines.append("   double m_risk;")
    lines.append("   int m_magic;")
    lines.append("public:")
    lines.append("   CBaseStrategy() : m_risk(0.01), m_magic(12345) {}")
    lines.append("   virtual ~CBaseStrategy() {}")
    lines.append("   virtual void Initialize() = 0;")
    lines.append("   virtual void Execute() = 0;")
    lines.append("   virtual void Cleanup() {}")
    lines.append("   double GetRisk() const { return m_risk; }")
    lines.append("   void SetRisk(double risk) { m_risk = risk; }")
    lines.append("  };")
    lines.append("")
    
    # Derived classes
    for i in range(10):
        lines.append(f"// Derived strategy class {i}")
        lines.append(f"class CDerivedStrategy{i} : public CBaseStrategy")
        lines.append("  {")
        lines.append("private:")
        lines.append(f"   int m_param{i};")
        lines.append("public:")
        lines.append(f"   CDerivedStrategy{i}() : m_param{i}(0) {{}}")
        lines.append(f"   virtual void Initialize() override {{ m_param{i} = 1; }}")
        lines.append(f"   virtual void Execute() override {{ m_param{i}++; }}")
        lines.append(f"   virtual void Cleanup() override {{ m_param{i} = 0; }}")
        lines.append(f"   int GetParam{i}() const {{ return m_param{i}; }}")
        lines.append("  };")
        lines.append("")
    
    # Abstract classes
    for i in range(5):
        lines.append(f"// Abstract class {i}")
        lines.append(f"class CAbstractHandler{i}")
        lines.append("  {")
        lines.append("public:")
        lines.append(f"   virtual void HandleTick(const MqlTick &tick) = 0;")
        lines.append(f"   virtual void HandleTrade(const MqlTradeTransaction &trans) = 0;")
        lines.append(f"   virtual string GetName() const = 0;")
        lines.append("  };")
        lines.append("")
    
    # Interface-like classes (pure virtual)
    for i in range(5):
        lines.append(f"// Interface {i}")
        lines.append(f"class IObserver{i}")
        lines.append("  {")
        lines.append("public:")
        lines.append(f"   virtual void OnUpdate{i}(int data) = 0;")
        lines.append(f"   virtual void OnRefresh{i}() = 0;")
        lines.append("  };")
        lines.append("")
    
    # Classes with properties
    for i in range(10):
        lines.append(f"// Class with properties {i}")
        lines.append(f"class CPropertyClass{i}")
        lines.append("  {")
        lines.append("private:")
        lines.append(f"   double m_value{i};")
        lines.append(f"   string m_name{i};")
        lines.append(f"   static int s_counter{i};")
        lines.append("public:")
        lines.append(f"   CPropertyClass{i}() : m_value{i}(0.0), m_name{i}(\"Object{i}\") {{ s_counter{i}++; }}")
        lines.append(f"   double GetValue() const {{ return m_value{i}; }}")
        lines.append(f"   void SetValue(double val) {{ m_value{i} = val; }}")
        lines.append(f"   string GetName() const {{ return m_name{i}; }}")
        lines.append(f"   void SetName(string name) {{ m_name{i} = name; }}")
        lines.append(f"   static int GetCounter{i}() {{ return s_counter{i}; }}")
        lines.append(f"   virtual void Process{i}() const {{ Print(\"Processing {i}\"); }}")
        lines.append("  };")
        lines.append(f"int CPropertyClass{i}::s_counter{i} = 0;")
        lines.append("")
    
    # Global variables
    lines.append("// Global variables")
    lines.append("CTrade g_trade;")
    lines.append("CPositionInfo g_position;")
    lines.append("CSymbolInfo g_symbol;")
    lines.append("CAccountInfo g_account;")
    lines.append("")
    
    for i in range(20):
        lines.append(f"CPropertyClass{i} g_object{i};")
    lines.append("")
    
    # Regular functions (50+)
    lines.append("// Regular functions")
    for i in range(60):
        lines.append(f"double CalculateValue{i}(int param1, double param2, string param3)")
        lines.append("  {")
        lines.append(f"   double result = param1 * param2;")
        lines.append(f"   if(StringLen(param3) > 0)")
        lines.append(f"      result += StringToDouble(param3);")
        lines.append(f"   return result / ({i + 1});")
        lines.append("  }")
        lines.append("")
    
    # Overloaded functions (30+)
    lines.append("// Overloaded functions")
    for i in range(35):
        base_name = f"OverloadedFunc{i}"
        lines.append(f"int {base_name}(int a)")
        lines.append("  {")
        lines.append(f"   return a * {i + 1};")
        lines.append("  }")
        lines.append("")
        lines.append(f"double {base_name}(double a, double b)")
        lines.append("  {")
        lines.append(f"   return a * b * {i + 1};")
        lines.append("  }")
        lines.append("")
        lines.append(f"string {base_name}(string s)")
        lines.append("  {")
        lines.append(f"   return StringFormat(\"Func{i}: %s\", s);")
        lines.append("  }")
        lines.append("")
    
    # Template functions (20+)
    lines.append("// Template functions")
    for i in range(25):
        lines.append(f"template<typename T>")
        lines.append(f"T TemplateFunc{i}(T value)")
        lines.append("  {")
        lines.append(f"   return value * {i + 1};")
        lines.append("  }")
        lines.append("")
        lines.append(f"template<typename T>")
        lines.append(f"T TemplateFunc{i}(T a, T b)")
        lines.append("  {")
        lines.append(f"   return (a + b) * {i + 1};")
        lines.append("  }")
        lines.append("")
    
    # Recursive functions (15+)
    lines.append("// Recursive functions")
    for i in range(20):
        lines.append(f"int RecursiveFunc{i}(int n)")
        lines.append("  {")
        lines.append(f"   if(n <= 1)")
        lines.append(f"      return 1;")
        lines.append(f"   return n * RecursiveFunc{i}(n - 1);")
        lines.append("  }")
        lines.append("")
    
    # Functions with array parameters
    lines.append("// Functions with array parameters")
    for i in range(15):
        lines.append(f"void ArrayFunc{i}(int &arr[], int size)")
        lines.append("  {")
        lines.append(f"   for(int j = 0; j < size; j++)")
        lines.append(f"      arr[j] = j * {i + 1};")
        lines.append("  }")
        lines.append("")
        lines.append(f"void RefFunc{i}(double &value)")
        lines.append("  {")
        lines.append(f"   value *= {i + 1.0};")
        lines.append("  }")
        lines.append("")
    
    # Functions with default parameters
    lines.append("// Functions with default parameters")
    for i in range(15):
        lines.append(f"void DefaultParamFunc{i}(int a = {i}, double b = {i}.0, string c = \"default\")")
        lines.append("  {")
        lines.append(f"   Print(\"DefaultParamFunc{i}: \", a, \" \", b, \" \", c);")
        lines.append("  }")
        lines.append("")
    
    # Event handlers
    lines.append("// MetaTrader Event Handlers")
    lines.append("")
    lines.append("int OnInit()")
    lines.append("  {")
    lines.append("   Print(\"Initializing...\");")
    lines.append("   g_symbol.Name(_Symbol);")
    lines.append("   EventSetTimer(1);")
    lines.append("   return(INIT_SUCCEEDED);")
    lines.append("  }")
    lines.append("")
    lines.append("void OnDeinit(const int reason)")
    lines.append("  {")
    lines.append("   Print(\"Deinitializing: \", reason);")
    lines.append("   EventKillTimer();")
    lines.append("  }")
    lines.append("")
    lines.append("void OnTick()")
    lines.append("  {")
    lines.append("   MqlTick tick;")
    lines.append("   if(SymbolInfoTick(_Symbol, SYMBOL_BID, tick.bid))")
    lines.append("     {")
    lines.append("      Print(\"Bid: \", tick.bid);")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    lines.append("void OnTimer()")
    lines.append("  {")
    lines.append("   static int counter = 0;")
    lines.append("   counter++;")
    lines.append("   Print(\"Timer tick: \", counter);")
    lines.append("  }")
    lines.append("")
    lines.append("void OnChartEvent(const int id, const long &lparam, const double &dparam, const string &sparam)")
    lines.append("  {")
    lines.append("   Print(\"Chart event: \", id);")
    lines.append("  }")
    lines.append("")
    lines.append("void OnBookEvent(const string &symbol)")
    lines.append("  {")
    lines.append("   Print(\"Book event for: \", symbol);")
    lines.append("  }")
    lines.append("")
    lines.append("void OnTradeTransaction(const MqlTradeTransaction &trans,")
    lines.append("                      const MqlTradeRequest &request,")
    lines.append("                      const MqlTradeResult &result)")
    lines.append("  {")
    lines.append("   Print(\"Trade transaction: \", trans.type);")
    lines.append("  }")
    lines.append("")
    lines.append("// Tester events")
    lines.append("int OnTesterInit()")
    lines.append("  {")
    lines.append("   Print(\"Tester init\");")
    lines.append("   return(0);")
    lines.append("  }")
    lines.append("")
    lines.append("void OnTesterDeinit()")
    lines.append("  {")
    lines.append("   Print(\"Tester deinit\");")
    lines.append("  }")
    lines.append("")
    lines.append("double OnTesterPass()")
    lines.append("  {")
    lines.append("   Print(\"Tester pass\");")
    lines.append("   return(0.0);")
    lines.append("  }")
    lines.append("")
    
    # Complex nested loops
    lines.append("// Complex nested loops function")
    lines.append("void ComplexNestedLoops()")
    lines.append("  {")
    lines.append("   for(int i = 0; i < 100; i++)")
    lines.append("     {")
    lines.append("      for(int j = 0; j < 50; j++)")
    lines.append("        {")
    lines.append("         for(int k = 0; k < 25; k++)")
    lines.append("           {")
    lines.append("            for(int l = 0; l < 10; l++)")
    lines.append("              {")
    lines.append("               for(int m = 0; m < 5; m++)")
    lines.append("                 {")
    lines.append("                  Print(i, \" \", j, \" \", k, \" \", l, \" \", m);")
    lines.append("                 }")
    lines.append("              }")
    lines.append("           }")
    lines.append("        }")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    
    # Complex conditional chains
    lines.append("// Complex conditional logic")
    lines.append("void ComplexConditionals(int value)")
    lines.append("  {")
    for i in range(25):
        if i == 0:
            lines.append(f"   if(value == {i})")
        else:
            lines.append(f"   else if(value == {i})")
        lines.append(f"     {{")
        lines.append(f"      Print(\"Value is {i}\");")
        lines.append(f"     }}")
    lines.append("   else")
    lines.append("     {")
    lines.append("      Print(\"Value is unknown\");")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    
    # Switch statements
    lines.append("// Large switch statement")
    lines.append("void LargeSwitch(int value)")
    lines.append("  {")
    lines.append("   switch(value)")
    lines.append("     {")
    for i in range(35):
        lines.append(f"      case {i}:")
        lines.append(f"         Print(\"Case {i}\");")
        lines.append(f"         break;")
    lines.append("      default:")
    lines.append("         Print(\"Default case\");")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    
    # Try-catch blocks
    lines.append("// Exception handling")
    lines.append("void ExceptionHandling()")
    lines.append("  {")
    lines.append("   try")
    lines.append("     {")
    lines.append("      try")
    lines.append("        {")
    lines.append("         throw(\"Test exception\");")
    lines.append("        }")
    lines.append("      catch(string e)")
    lines.append("        {")
    lines.append("         Print(\"Inner catch: \", e);")
    lines.append("        }")
    lines.append("     }")
    lines.append("   catch(string e)")
    lines.append("     {")
    lines.append("      Print(\"Outer catch: \", e);")
    lines.append("     }")
    lines.append("   finally")
    lines.append("     {")
    lines.append("      Print(\"Finally block\");")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    
    # Multi-dimensional arrays
    lines.append("// Multi-dimensional array operations")
    lines.append("void MultiDimensionalArrays()")
    lines.append("  {")
    lines.append("   int array2d[10][10];")
    lines.append("   int array3d[5][5][5];")
    lines.append("   double array4d[3][3][3][3];")
    lines.append("   ")
    lines.append("   for(int i = 0; i < 10; i++)")
    lines.append("     {")
    lines.append("      for(int j = 0; j < 10; j++)")
    lines.append("        {")
    lines.append("         array2d[i][j] = i * j;")
    lines.append("        }")
    lines.append("     }")
    lines.append("   ")
    lines.append("   for(int i = 0; i < 5; i++)")
    lines.append("     {")
    lines.append("      for(int j = 0; j < 5; j++)")
    lines.append("        {")
    lines.append("         for(int k = 0; k < 5; k++)")
    lines.append("           {")
    lines.append("            array3d[i][j][k] = i + j + k;")
    lines.append("           }")
    lines.append("        }")
    lines.append("     }")
    lines.append("  }")
    lines.append("")
    
    # More functions to reach 10,000+ lines
    lines.append("// Additional utility functions")
    for i in range(100):
        lines.append(f"void UtilityFunction{i}(int param)")
        lines.append("  {")
        lines.append(f"   // Function body {i}")
        for j in range(10):
            lines.append(f"   int local{j} = param * {j + 1};")
            lines.append(f"   Print(\"Local{j} = \", local{j});")
        lines.append("  }")
        lines.append("")
    
    # More complex functions
    for i in range(50):
        lines.append(f"double ComplexCalculation{i}(double input)")
        lines.append("  {")
        lines.append(f"   double result = input;")
        for j in range(15):
            lines.append(f"   result = MathSin(result) * {j + 1};")
            lines.append(f"   result = MathCos(result) + {j + 1};")
        lines.append(f"   return result;")
        lines.append("  }")
        lines.append("")
    
    # Standard library usage examples
    lines.append("// Standard library usage")
    lines.append("void UseStandardLibrary()")
    lines.append("  {")
    lines.append("   // CTrade usage")
    lines.append("   g_trade.Buy(1.0, _Symbol, 0, 0, 0, \"Buy order\");")
    lines.append("   g_trade.Sell(1.0, _Symbol, 0, 0, 0, \"Sell order\");")
    lines.append("   g_trade.PositionClose(_Symbol);")
    lines.append("   ")
    lines.append("   // Indicator usage")
    lines.append("   int handle_ma = iMA(_Symbol, PERIOD_CURRENT, 20, 0, MODE_SMA, PRICE_CLOSE);")
    lines.append("   int handle_rsi = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);")
    lines.append("   int handle_macd = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE);")
    lines.append("   ")
    lines.append("   // Time functions")
    lines.append("   MqlDateTime dt;")
    lines.append("   TimeToStruct(TimeCurrent(), dt);")
    lines.append("   Print(dt.year, \"-\", dt.mon, \"-\", dt.day);")
    lines.append("  }")
    lines.append("")
    
    # Add more filler to ensure 10,000+ lines
    lines.append("// Additional code blocks for line count")
    for i in range(50):
        lines.append(f"void FillerBlock{i}()")
        lines.append("  {")
        for j in range(30):
            lines.append(f"   int var{i}_{j} = {i * j};")
            lines.append(f"   Print(\"Variable {i}_{j} = \", var{i}_{j});")
        lines.append("  }")
        lines.append("")
    
    print(f"Generated {len(lines)} lines")
    return '\n'.join(lines)


if __name__ == "__main__":
    content = generate_large_mql5_file()
    
    # Write to test fixtures directory
    output_path = "tests/fixtures/large_test_file.mq5"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Written to {output_path}")
    print(f"Total lines: {content.count(chr(10)) + 1}")
